steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp requirements.txt src/cloud_functions/inputs/ && \
        pip install -r src/cloud_functions/inputs/requirements.txt

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd src/cloud_functions/inputs && \
        gcloud functions deploy upload_csv_to_bigquery_inputs \
        --runtime python310 \
        --trigger-http \
        --allow-unauthenticated \
        --region southamerica-east1 \
        --memory 256MB \
        --source .

timeout: 900s  # 15 minutes for the build to complete
options:
  logging: CLOUD_LOGGING_ONLY  # Use only Cloud Logging
