steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp requirements.txt src/cloud_functions/import/

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd src/cloud_functions/import && \
        gcloud functions deploy store_import_data \
        --runtime python310 \
        --trigger-http \
        --allow-unauthenticated \
        --region southamerica-east1 \
        --memory 256MB \
        --source . \
        --entry-point store_import_data \
        --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com


timeout: 900s  # 15 minutes for the build to complete
options:
  logging: CLOUD_LOGGING_ONLY  # Use only Cloud Logging
