steps:
  # Step 1: Install dependencies using a Python container
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  # Step 2: Use gcloud container to deploy the Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy trigger_shipping_cost \
        --runtime python310 \
        --trigger-http \
        --allow-unauthenticated \
        --entry-point main_costs.py \
        --region southamerica-east1 \
        --memory 256MB \
        --source src/cloud_functions/fetch_data


# Configuration
timeout: 900s  # 15 minutes for the build to complete
options:
  logging: CLOUD_LOGGING_ONLY  # Use only Cloud Logging
