steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp requirements.txt ${_FUNCTION_PATH}

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd ${_FUNCTION_PATH} && \
        gcloud functions deploy ${_FUNCTION_NAME} \
        --gen2 \
        --runtime python310 \
        --trigger-http \
        --allow-unauthenticated \
        --region southamerica-east1 \
        --memory 256MB \
        --source . \
        --entry-point ${_FUNCTION_NAME} \
        --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
        --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com


timeout: 900s  # 15 minutes for the build to complete
options:
  logging: CLOUD_LOGGING_ONLY