steps:
  # Passo 1: Usar contêiner Python para instalar dependências
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  # Passo 2: Usar o contêiner gcloud para fazer o deploy da Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - |
        gcloud functions deploy trigger_shipping_cost \
        --runtime python310 \
        --trigger-http \
        --allow-unauthenticated \
        --entry-point main_shipping_cost \
        --source src/cloud_functions/fetch_data \
        --region southamerica-east1 \
        --memory 256MB

# Configurações
timeout: 900s  # Tempo limite para o build ser concluído (15 minutos)
options:
  logging: CLOUD_LOGGING_ONLY  # Usar apenas Cloud Logging
