steps:
  # Step to install dependencies and cache them
  - name: 'python:3.10'
    id: 'install-dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt --cache-dir=/workspace/.pip-cache

  # # Deploy fetch_history_orders function in parallel
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-fetch-history-orders'
  #   waitFor: ['install-dependencies']
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cp requirements.txt src/cloud_functions/_1_fetch_data/_0_1_fetch_history_orders && \
  #       mkdir -p src/cloud_functions/_1_fetch_data/_0_1_fetch_history_orders/src && \
  #       cp -r src/common src/cloud_functions/_1_fetch_data/_0_1_fetch_history_orders/src && \
  #       cp -r src/config src/cloud_functions/_1_fetch_data/_0_1_fetch_history_orders/src && \
  #       cd src/cloud_functions/_1_fetch_data/_0_1_fetch_history_orders && \
  #       gcloud functions deploy fetch_history_orders \
  #       --gen2 \
  #       --runtime python310 \
  #       --trigger-http \
  #       --no-allow-unauthenticated \
  #       --region southamerica-east1 \
  #       --memory 512MB \
  #       --timeout 3600 \
  #       --source . \
  #       --entry-point fetch_history_orders \
  #       --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
  #       --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com


  # Deploy fetch_items function in parallel
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-fetch-items'
  #   waitFor: ['install-dependencies']
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cp requirements.txt src/cloud_functions/_1_fetch_data/_1_0_fetch_items && \
  #       mkdir -p src/cloud_functions/_1_fetch_data/_1_0_fetch_items/src && \
  #       cp -r src/common src/cloud_functions/_1_fetch_data/_1_0_fetch_items/src && \
  #       cp -r src/config src/cloud_functions/_1_fetch_data/_1_0_fetch_items/src && \
  #       cd src/cloud_functions/_1_fetch_data/_1_0_fetch_items && \
  #       gcloud functions deploy fetch_items \
  #       --gen2 \
  #       --runtime python310 \
  #       --trigger-http \
  #       --no-allow-unauthenticated \
  #       --region southamerica-east1 \
  #       --memory 512MB \
  #       --timeout 3600 \
  #       --source . \
  #       --entry-point fetch_items_data \
  #       --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
  #       --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

  # # Deploy fetch_details function in parallel
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-fetch-details'
  #   waitFor: ['install-dependencies']
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cp requirements.txt src/cloud_functions/_1_fetch_data/_1_1_fetch_details && \
  #       mkdir -p src/cloud_functions/_1_fetch_data/_1_1_fetch_details/src && \
  #       cp -r src/common src/cloud_functions/_1_fetch_data/_1_1_fetch_details/src && \
  #       cp -r src/config src/cloud_functions/_1_fetch_data/_1_1_fetch_details/src && \
  #       cd src/cloud_functions/_1_fetch_data/_1_1_fetch_details && \
  #       gcloud functions deploy fetch_details \
  #       --gen2 \
  #       --runtime python310 \
  #       --trigger-http \
  #       --no-allow-unauthenticated \
  #       --region southamerica-east1 \
  #       --memory 512MB \
  #       --timeout 3600 \
  #       --source . \
  #       --entry-point fetch_details_data \
  #       --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
  #       --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

  # # Deploy fetch_variations function in parallel
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-fetch-variations'
  #   waitFor: ['install-dependencies']
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cp requirements.txt src/cloud_functions/_1_fetch_data/_1_10_fetch_variations && \
  #       mkdir -p src/cloud_functions/_1_fetch_data/_1_10_fetch_variations/src && \
  #       cp -r src/common src/cloud_functions/_1_fetch_data/_1_10_fetch_variations/src && \
  #       cp -r src/config src/cloud_functions/_1_fetch_data/_1_10_fetch_variations/src && \
  #       cd src/cloud_functions/_1_fetch_data/_1_10_fetch_variations && \
  #       gcloud functions deploy fetch_variations \
  #       --gen2 \
  #       --runtime python310 \
  #       --trigger-http \
  #       --no-allow-unauthenticated \
  #       --region southamerica-east1 \
  #       --memory 512MB \
  #       --timeout 3600 \
  #       --source . \
  #       --entry-point fetch_variations_data \
  #       --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
  #       --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

  # # Deploy fetch_costs function in parallel
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-fetch-costs'
  #   waitFor: ['install-dependencies']
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cp requirements.txt src/cloud_functions/_1_fetch_data/_1_2_fetch_costs && \
  #       mkdir -p src/cloud_functions/_1_fetch_data/_1_2_fetch_costs/src && \
  #       cp -r src/common src/cloud_functions/_1_fetch_data/_1_2_fetch_costs/src && \
  #       cp -r src/config src/cloud_functions/_1_fetch_data/_1_2_fetch_costs/src && \
  #       cd src/cloud_functions/_1_fetch_data/_1_2_fetch_costs && \
  #       gcloud functions deploy fetch_costs \
  #       --gen2 \
  #       --runtime python310 \
  #       --trigger-http \
  #       --no-allow-unauthenticated \
  #       --region southamerica-east1 \
  #       --memory 512MB \
  #       --timeout 3600 \
  #       --source . \
  #       --entry-point fetch_costs_data \
  #       --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
  #       --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

#   # Deploy fetch_catalog function in parallel
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     id: 'deploy-fetch-catalog'
#     waitFor: ['install-dependencies']
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp requirements.txt src/cloud_functions/_1_fetch_data/_1_3_fetch_catalog && \
#         mkdir -p src/cloud_functions/_1_fetch_data/_1_3_fetch_catalog/src && \
#         cp -r src/common src/cloud_functions/_1_fetch_data/_1_3_fetch_catalog/src && \
#         cp -r src/config src/cloud_functions/_1_fetch_data/_1_3_fetch_catalog/src && \
#         cd src/cloud_functions/_1_fetch_data/_1_3_fetch_catalog && \
#         gcloud functions deploy fetch_catalog \
#         --gen2 \
#         --runtime python310 \
#         --trigger-http \
#         --no-allow-unauthenticated \
#         --region southamerica-east1 \
#         --memory 512MB \
#         --timeout 3600 \
#         --source . \
#         --entry-point fetch_catalog_data \
#         --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
#         --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

#   # Deploy fetch_fulfillment function in parallel
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     id: 'deploy-fetch-fulfillment'
#     waitFor: ['install-dependencies']
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp requirements.txt src/cloud_functions/_1_fetch_data/_1_4_fetch_fullfilment && \
#         mkdir -p src/cloud_functions/_1_fetch_data/_1_4_fetch_fullfilment/src && \
#         cp -r src/common src/cloud_functions/_1_fetch_data/_1_4_fetch_fullfilment/src && \
#         cp -r src/config src/cloud_functions/_1_fetch_data/_1_4_fetch_fullfilment/src && \
#         cd src/cloud_functions/_1_fetch_data/_1_4_fetch_fullfilment && \
#         gcloud functions deploy fetch_fullfilment \
#         --gen2 \
#         --runtime python310 \
#         --trigger-http \
#         --no-allow-unauthenticated \
#         --region southamerica-east1 \
#         --memory 512MB \
#         --timeout 3600 \
#         --source . \
#         --entry-point fetch_fullfilment_data \
#         --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
#         --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

#   # Deploy fetch_prices function in parallel
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-fetch-prices'
    waitFor: ['install-dependencies']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp requirements.txt src/cloud_functions/_1_fetch_data/_1_5_fetch_prices && \
        mkdir -p src/cloud_functions/_1_fetch_data/_1_5_fetch_prices/src && \
        cp -r src/common src/cloud_functions/_1_fetch_data/_1_5_fetch_prices/src && \
        cp -r src/config src/cloud_functions/_1_fetch_data/_1_5_fetch_prices/src && \
        cd src/cloud_functions/_1_fetch_data/_1_5_fetch_prices && \
        gcloud functions deploy fetch_prices \
        --gen2 \
        --runtime python310 \
        --trigger-http \
        --no-allow-unauthenticated \
        --region southamerica-east1 \
        --memory 512MB \
        --timeout 3600 \
        --source . \
        --entry-point fetch_prices_data \
        --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
        --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com


  # Deploy fetch_shipping_cost function in parallel
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-fetch-shipping-cost'
  #   waitFor: ['install-dependencies']
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cp requirements.txt src/cloud_functions/_1_fetch_data/_1_6_fetch_shipping_cost && \
  #       mkdir -p src/cloud_functions/_1_fetch_data/_1_6_fetch_shipping_cost/src && \
  #       cp -r src/common src/cloud_functions/_1_fetch_data/_1_6_fetch_shipping_cost/src && \
  #       cp -r src/config src/cloud_functions/_1_fetch_data/_1_6_fetch_shipping_cost/src && \
  #       cd src/cloud_functions/_1_fetch_data/_1_6_fetch_shipping_cost && \
  #       gcloud functions deploy fetch_shipping_cost \
  #       --gen2 \
  #       --runtime python310 \
  #       --trigger-http \
  #       --no-allow-unauthenticated \
  #       --region southamerica-east1 \
  #       --memory 512MB \
  #       --timeout 3600 \
  #       --source . \
  #       --entry-point fetch_shipping_cost_data \
  #       --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
  #       --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

#   # Deploy fetch_competitors_price function in parallel
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     id: 'deploy-fetch-competitors-price'
#     waitFor: ['install-dependencies']
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp requirements.txt src/cloud_functions/_1_fetch_data/_1_7_fetch_competitors_price && \
#         mkdir -p src/cloud_functions/_1_fetch_data/_1_7_fetch_competitors_price/src && \
#         cp -r src/common src/cloud_functions/_1_fetch_data/_1_7_fetch_competitors_price/src && \
#         cp -r src/config src/cloud_functions/_1_fetch_data/_1_7_fetch_competitors_price/src && \
#         cd src/cloud_functions/_1_fetch_data/_1_7_fetch_competitors_price && \
#         gcloud functions deploy fetch_competitors_price \
#         --gen2 \
#         --runtime python310 \
#         --trigger-http \
#         --no-allow-unauthenticated \
#         --region southamerica-east1 \
#         --memory 512MB \
#         --timeout 3600 \
#         --source . \
#         --entry-point fetch_competitors_prices_data \
#         --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
#         --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

#   # Deploy fetch_orders function in parallel
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     id: 'deploy-fetch-orders'
#     waitFor: ['install-dependencies']
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp requirements.txt src/cloud_functions/_1_fetch_data/_1_8_fetch_orders && \
#         mkdir -p src/cloud_functions/_1_fetch_data/_1_8_fetch_orders/src && \
#         cp -r src/common src/cloud_functions/_1_fetch_data/_1_8_fetch_orders/src && \
#         cp -r src/config src/cloud_functions/_1_fetch_data/_1_8_fetch_orders/src && \
#         cd src/cloud_functions/_1_fetch_data/_1_8_fetch_orders && \
#         gcloud functions deploy fetch_orders \
#         --gen2 \
#         --runtime python310 \
#         --trigger-http \
#         --no-allow-unauthenticated \
#         --region southamerica-east1 \
#         --memory 512MB \
#         --timeout 3600 \
#         --source . \
#         --entry-point fetch_orders_data \
#         --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
#         --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

#   # Deploy fetch_competitors_details function in parallel
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     id: 'deploy-fetch-competitors-details'
#     waitFor: ['install-dependencies']
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp requirements.txt src/cloud_functions/_1_fetch_data/_1_9_fetch_competitors_details && \
#         mkdir -p src/cloud_functions/_1_fetch_data/_1_9_fetch_competitors_details/src && \
#         cp -r src/common src/cloud_functions/_1_fetch_data/_1_9_fetch_competitors_details/src && \
#         cp -r src/config src/cloud_functions/_1_fetch_data/_1_9_fetch_competitors_details/src && \
#         cd src/cloud_functions/_1_fetch_data/_1_9_fetch_competitors_details && \
#         gcloud functions deploy fetch_competitors_details \
#         --gen2 \
#         --runtime python310 \
#         --trigger-http \
#         --no-allow-unauthenticated \
#         --region southamerica-east1 \
#         --memory 512MB \
#         --timeout 3600 \
#         --source . \
#         --entry-point fetch_competitors_details_data \
#         --service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com \
#         --run-service-account data-lake-v2@datalake-v2-424516.iam.gserviceaccount.com

timeout: 3600s  # 30 minutos de timeout para o build completo
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  volumes:
    - name: 'pip-cache'
      path: /workspace/.pip-cache
